version: '3.8'

services :

  mysql:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysqldb
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: bewee_db
    ports:
      - "3306:3306"

  UserApplication:
    image: user-application
    container_name: user-application
    build:
      context: ../UserApplication
      dockerfile: dockerfile
    ports:
      - "9011:9011"

volumes:
  db_data: { }
